# Configuração de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=/ext!00x
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
# ^ Essa linha permite criar tabelas no banco de dados automaticamente assim que as classes forem criadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true